# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.hostname = "ubuntu"
  
    ############################################################
    # Provider for Docker on Intel or ARM (aarch64)
    ############################################################
    config.vm.provider :docker do |docker, override|
      override.vm.box = nil
      docker.image = "rofrano/vagrant-provider:ubuntu"
      docker.remains_running = true
      docker.has_ssh = true
      docker.privileged = true
      # config.vm.network "forwarded_port", guest: 80, host: 80
      # config.vm.network "forwarded_port", guest: 8080, host: 8080
      config.vm.network "forwarded_port", guest: 1883, host: 1883
      # config.vm.network "forwarded_port", guest: 3306, host: 3306
      config.vm.network "forwarded_port", guest: 9001, host: 9001
      docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
      docker.create_args = ["--cgroupns=host"]
      # Uncomment to force arm64 for testing images on Intel
      # docker.create_args = ["--platform=linux/arm64", "--cgroupns=host"]     
    end  
    config.vm.provision "file", source: "base.sh", destination: "base.sh"  

    config.vm.provision "shell", inline: <<-SHELL
    sh base.sh
    SHELL

    # Install Docker and pull an image
    # config.vm.provision :docker do |d|
    #   d.pull_images "alpine:latest"
    # end
  
  end
  